name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    permissions: write-all
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 1

      - uses: actions/checkout@v3
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 15.4
      - run: cd iosApp
      - run: xcodebuild -version

    #      - name: Xcode Select Version
#        uses: mobiledevops/xcode-select-version-action@v1
#        with:
#          xcode-select-version: '14.2'

#      - name: Select latest Xcode
#        uses: maxim-lobanov/setup-xcode@v1
#        with:
#          xcode-version: '14.2'

#      - run: xcodebuild -version

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install
          pod setup

      - name: Build and Analyze
        run: |
          xcodebuild -version
          xcodebuild build -workspace iosApp.xcodeproj/project.xcworkspace -scheme iosApp -destination "OS=16.4,name=iPhone 14" -configuration Debug
